name: Timelapse
on:
  push: {}
  schedule:
    - cron: '0 1 * * *'
jobs:
  timelapse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install emoji support
        run: |
          sudo apt-get install fonts-noto-color-emoji -y
      - run: yarn
      - run: node main.js
      - name: Some Git wizardry
        run: |
          git add --all \
            && (git diff --cached --name-only | tee /tmp/changes.filelist.txt) \
            && git commit -m "📸 $(node -p 'new Date().toJSON()') [$(node -p '(fs.readFileSync("/tmp/changes.filelist.txt", "utf-8").match(/\S+/g) || []).map(x => path.basename(x, ".png")).join(", ")')]" \
            || echo "Nothing to commit"
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" "$GITHUB_REF"
        env:
          GIT_COMMITTER_NAME: Janitor
          GIT_AUTHOR_NAME: Janitor
          EMAIL: repository-janitor[bot]@users.noreply.github.com
      - run: |
          node << 'EOF'
            const fs = require('fs')
            const { execSync } = require('child_process')
            const filelist = "/tmp/changes.filelist.txt"
            const changed = (fs.existsSync(filelist) && fs.readFileSync("/tmp/changes.filelist.txt", "utf-8").match(/\S+\.png/g)) || []
            const head = String(execSync('git rev-parse HEAD')).trim()
            for (const filename of changed) {
              console.log(filename)
              const url = `https://github.com/${{ github.repository }}/raw/${head}/${filename}`
              const input = JSON.stringify({
                text: `Updated ${filename}`,
                blocks: [
                  { type: 'section', text: { type: 'mrkdwn', text: `<${url}|${filename}>` } },
                  { type: 'image', alt_text: filename, image_url: url },
                ]
              })
              console.log(input)
              try {
                execSync('curl -X POST -H "Content-type: application/json" -d @- "${{ secrets.SLACK_WEBHOOK_URL }}"', {
                  input,
                  stdio: ['pipe', 'inherit', 'inherit']
                })
              } catch (error) {
                console.error(error)
              }
            }
          EOF
