name: Timelapse
on:
  push: {}
  schedule:
    - cron: '0 1 * * *'
jobs:
  timelapse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: sudo apt install fonts-noto
      - run: yarn
      - run: node main.js
      - name: Some Git wizardry
        run: |
          git add -A
          git add --all \
            && git commit -m "📸 $(node -p 'new Date().toJSON()') [$(node -p 'String(child_process.execSync("git diff --cached --name-only")).match(/\S+/g).map(x => path.basename(x, ".png")).join(", ")')]" \
            || echo "Nothing to commit"
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" "$GITHUB_REF"
        env:
          GIT_COMMITTER_NAME: Janitor
          GIT_AUTHOR_NAME: Janitor
          EMAIL: repository-janitor[bot]@users.noreply.github.com
